project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  typst: default
  docx: default
  jats: default

  # (other formats)
  pdf: default

execute:
  freeze: true
